### ISSUE TITLE
No nodes created - bug or stupidity?

### ISSUE THREAD

**Issue by markusvoelter** [ModelingValueGroup/DclareForMPS#1]
![Screenshot 2019-10-18 at 12 05 25](https://user-images.githubusercontent.com/592330/67085697-9990ab80-f19f-11e9-81bd-8a83c40923f5.png)

I am assuming that this ruleset 
* produces instances of ValidationInspector as roots in the current model, one for each instance of TaxModule in that same model

But nothing happens ... even though the Engine is activated in the preferences.

**Comment by WimBast** [comment]
I have created the following rule as the only rule in the language:

  this.roots(Type) := this.roots(Model).select({~m => 
    System.err.println("!!!!!!!!!!!!!!!!!!!!"); 
    <Class( 
      name: m.name, 
      fields: # m.descendants<concept = NonLexicalObjectType>.select({~r => <Field( 
          name: r.name, 
          type: # null 
        )>; }) 
    )>; 
  });

It works fine. In which language did you create the rule?
  
}

**Comment by markusvoelter** [comment]
I have created it in a customer language. Yes, that language is imported ("used languages") in my model. So it is also in my solution. But nothing happens.

**Comment by WimBast** [comment]
Is there any concept instantiated in your solution that is defined in the same language as your rule is?

**Comment by markusvoelter** [comment]
Yes, of course. All the concepts mentioned in my example above are in that same language that also has the rules.

**Comment by WimBast** [comment]
What happens if you rebuild the whole project? This is forcing the Dclare engine to refresh the solutions and models to activate the rules on the right models. (Should work automatically though)

**Comment by markusvoelter** [comment]
I have created a hello-world language, in a separate project. After a rebuild, the synchronization started. But still no luck with the customer language.

**Comment by WimBast** [comment]
Do you have the two projects open simultaneously?

**Comment by markusvoelter** [comment]
No.

**Comment by WimBast** [comment]
No messages in the 'Dclare Messages' tool tab?

**Comment by markusvoelter** [comment]
It is empty.

**Comment by WimBast** [comment]
Can you share more about the customer project? Any other rules? Nr of ValidationRules per  TaxModule? Perhaps the descendants construct causes problems if a TaxModule is to big.

**Comment by markusvoelter** [comment]
Do you want to screenshare? I don't see us making progress this way.

**Comment by WimBast** [comment]
Yes

**Comment by markusvoelter** [comment]
Sent an invite.

**Comment by WimBast** [comment]
Where to?

**Comment by markusvoelter** [comment]
your gmail

**Comment by markusvoelter** [comment]
Heres the link: https://hangouts.google.com/call/UYrOmtXMwcDhVuwc-fpiAEEI

**Comment by WimBast** [comment]
I have created a new version with some bug-fixes to improve stability and to show the inconsistency-messages properly.
