### ISSUE TITLE
Minor bug in DShape_GUI

### ISSUE THREAD

**Issue by wuryel** [ModelingValueGroup/dclareForMPS#128]
Installed plugin release 3.0.1 from Jetbrains Marketplace.

There is a minor bug in DShape_GUI:
The attribute `hitRight` should be assigned true here.  `hitRight := true;` instead of `hitLeft := true;`
http://127.0.0.1:63320/node?ref=r%3A3ec44d77-eb4f-4600-add0-5e671af45a7b%28DclareGui.rules%29%2F2526773219035106274

**Comment by WimBast** [comment]
Fixed in develop
