### ISSUE TITLE
How to use the inverse relation operator (~)?

### ISSUE THREAD

**Issue by enikao** [ModelingValueGroup/DclareForMPS#4]
You showed this operator in the demo. I found the concept, but I cannot instantiate it.

Side note: If I understood the concept correctly, the operator currently only supports multi-valued links. What about single-valued ones?

**Comment by WimBast** [comment]
It actually only support references. E.g. on Nodes that references single other node. You can just use the parent construct to navigate to the opposite of children.

**Comment by WimBast** [comment]
You need the structure of the language that you want to navigate imported in your Rule aspect model

**Comment by WimBast** [comment]
Dit you get the ~ working?

**Comment by enikao** [comment]
No, but I also didn't try that hard.

Did I get it correctly, the `~` operator is essentially the same as `node.parent`?
What's the big advantage of that?

I hoped for one of these:

1. `A` has a reference `x` to `B`, and I can get the backwards reference efficiently (might be multivalued, i.e. `A -x-> B` and `C -x-> B`, therefore `~xB` is `{A, C}`)
2. `A` is in the original model, and I create `B` with Dclare. Then `~B` is `A`.

**Comment by WimBast** [comment]
Sorry for the misunderstanding, indeed the ~ is used to navigate in the opposite direction of references of nodes. Hence, not for navigating the opposite of children. What I meant is that you already can use the parent construct for that. So it is exactly what you expect.

I am still curious why it dit not work in your case. Can you give me the example?

**Comment by enikao** [comment]
It's in my "DetailsBack" example, branch `master`, rule for `IOverridable`.
I want to get all ``Override``s that point to my `IOverridable` via `Override.overrides`.

I tried to work around it with this ugliness (it's missing the filter to find only the ones pointing to `this`):

![image](https://user-images.githubusercontent.com/2211690/67273398-a45c8080-f4be-11e9-954d-e27cfc3b6fe3.png)

**Comment by WimBast** [comment]
I could see it in the scope menu. I wander why you do not see it. It is named ~overrides

![tilde](https://user-images.githubusercontent.com/35731966/67275396-cbb54c80-f4c2-11e9-8c5c-4f60fc3915f1.jpg)

Also make the attribute optional, because otherwise you get an inconsistency error when it is null (which may intentionally be the case here).

**Comment by enikao** [comment]
Aah, I thought it to be a prefix operator like `~this.Override::overrides.first` or something.

This way, it works for me too.
