### ISSUE TITLE
Identity of struct not recognized

### ISSUE THREAD

**Issue by enikao** [ModelingValueGroup/DclareForMPS#41]
Example model: https://github.com/enikao/dclare4mps-n-to-m-mapping

I'm trying to implement a n:m mapping.

Scenario: We have a tree structure as source.
We can define several configurations for each tree. A configuration mirrors the source tree structure, and we can add some attributes  to each mirrored node.

Dclare should make sure all configurations are in sync with the tree.

I get the following error message:
````
REFERENCED_ORPHAN Property 'triple' of object 'A config alpha' references orphan 'Triple[A, A config alpha]' in RootTreeConfig#whia2g0jaqe7           
````

Each config refers to its own `Triple`, so how can this happen?

**Comment by WimBast** [comment]
I have created a fork with some fixes in the rules only and created a pull request. I included comments with explanations where the rules where changed.

Any referenced module, model, node or struct must be contained, otherwise you get an orphan error. Structs can be contained by a 'composite' attribute.

**Comment by WimBast** [comment]
I am not sure why you concluded that the identity of the struct is not recognized.

**Comment by WimBast** [comment]
Hi Niko, does it work for you now?

**Comment by enikao** [comment]
> I am not sure why you concluded that the identity of the struct is not recognized.

I thought it would not recognize that the two structs in question are indeed the same.

> Hi Niko, does it work for you now?

Yes, thanks a lot!
Although I would never have figured out the `composite` attribute on my own.
