### ISSUE TITLE
Smart References through menu don't work properly

### ISSUE THREAD

**Issue by Gattag** [ModelingValueGroup/dclareForMPS#49]
### Versions
- MPS = 2021.1.3
- DclareForMPS = 1.6.1 (plugin installed through JetBrains plugin marketplace)

### Issue
When selecting a smart reference through the completion menu, the node is created, the reference looks like it is populated for a fraction of a second, but it is instantly removed (I don't know enough about MPS internals to tell you if that is just a rendered placeholder from the completion menu or if the node actually has the link and it is removed momentarily afterward). This happens only when there is at least one ruleset (even if it is blank) and the engine is on.

### Reproduce
I made a small language with variable definition statements and variable reference expressions to demonstrate the issue
[dclare-smart-ref-test](https://github.com/Gattag/dclare-smart-ref-test)

### Other notes
On a completely unrelated (I think, but maybe they are the same thing) note, undo is impossible after any change is preformed by Dclare. Is this a know issue, am I dumb, or is this not intended? Thanks, G

**Comment by WimBast** [comment]
Fixed (cannot reproduce anymore in last release).
On tother note: Also the problems with undo are fixed.
