### ISSUE TITLE
Example of optional details not working

### ISSUE THREAD

**Issue by enikao** [ModelingValueGroup/DclareForMPS#5]
I created a simple example:

Language **Coarse** describes a `Container`.
Language **Fine** describes the same thing, but on a higher detail level: `DetailedContainer`.

The Dclare transformation creates from a `Container` a `DetailedContainer` and adds some ``IDetail``s.
This part works.

In a `Container`, I can add ``Override``s. They can override any `IOverridable`, amongst them `IDetail`.
This part doesn't work.

In the rule, I have log messages in both the *if* and the *else* branch, but neither is shown.

How to find out what's the issue?

(This example also shows #4)

https://github.com/enikao/DclareForMPS-DetailsBack

**Comment by enikao** [comment]
In branch *TransactionException* I rewrote the Dclare statement to be based on `Override`, not `IOverridable` as before. Now it's at least doing something: Throwing an `TransactionException` ...

**Comment by enikao** [comment]
The *real* idea behind this example: As soon as the user changes some `IOverridable` in the `DetailedContainer`, we automatically create an `Override` in the corresponding `Container` to record the change.

This way, the user doesn't need to care about default details, but can override the deviating ones.

**Comment by WimBast** [comment]
You are calling a behavior-method (override) with a site-effect in a declarative rule. That simply does not work. You need to define any model-change using ':=' and ':=' is only allowed in rule-sets. Calling behavior-methods is fine if they are read-only and are reading only a small part of your model (the latter only for performance reasons).

**Comment by WimBast** [comment]
Also throwing messages (in the master branch) will not work, but i dit not try that yet.

**Comment by WimBast** [comment]
I do think we should give better feet-back in our messages for this.

**Comment by WimBast** [comment]
I have found the cause why the messages not showing up and i will create a new release soon.

**Comment by WimBast** [comment]
Interestingly it does work but your two rule are in conflict:
Remember that all statement in Dclare are invariants. This means that one rule sets it to 'red' and the other to 'yellow' These to riles are in cloflict (they cannot be both true). This causes a nice message that sadly is not show in the messages (you get the exception in place).  That is wat i am now fixing.

**Comment by enikao** [comment]
I added a branch *working* that contains a working example.

**Comment by WimBast** [comment]
Nice example onikao, thanks!
In release v0.99.1a the 'conflicting rules' messages are shown again. You can cntr-click on the message to jump to the conflicting rule and trace back the cause of the conflict by opening the child-rules.

**Comment by WimBast** [comment]
````
foreach d in details { 
  if (d.isDefault()) { 
    d.value := d.defaultValue; 
  } 
}
````
Why dit you put this in a foreach-statement instead of a rule (see below) in StringDetail rule-set? That will give a finer granularity of incremental updates and parallel rule-execution.
````
  if (this.isDefault()) { 
    this.value := this.defaultValue; 
  } 
````

**Comment by enikao** [comment]
I think I ended up to do everything at the `Container` because I couldn't get the `~` operator working.

I changed the example to your proposal.
