### ISSUE TITLE
contains() relation?

### ISSUE THREAD

**Issue by enikao** [ModelingValueGroup/DclareForMPS#6]
I'd like to write a rule that makes sure a node contains my node, i.e. either creates it or refers the existing one.

In the example of #5, assume `Container.override` contains, next to `Override`, also `FakeOverride` (to be added by the user). Currently, I can create my ``Overrides`` only by assignment:

````
container.override := listOfAllOverrides;
````

I'd like to write something like:

````
// variant A
container.overrides.contains(myPotentiallyNewOverride);
// variant B
container.overrides.containsAll(listOfAllOverrides);
````

This would keep existing ``FakeOverride``s, but add new ``Override``s if required.

Probably a new operator would be more fitting than `contains()` / `containsAll()`.

**Comment by WimBast** [comment]
You can assign the concatenation of your fake override and all other overrides. This will also ensure that if a user removes a non-fake override it will be removed from the overrides. Remember all equations are invariants. They not only work for adding but also removing. 

You kan also create equations that are conditional by placing them in a 'if' statement. Then they keep the value untuched when the condition not holds.

**Comment by enikao** [comment]
Assume `this.overrides` contains both ``Override``s and ``FakeOverride``s (*Fake* because they don't override anything, they are used for some other purpose). `FakeOverride` should never be touched by Dclare, i.e. neither added or removed.
But Dclare *should* create other members of the collection, if required.
It's a bit similar to `findOrCreateModel()`, with matching identity rather than name --> `findOrCreateNode()`.

I tried something like this, but it didn't work:

````
// attributes
nlist<Override> currentOverrides := this.overrides;
node<Override> o = currentOverrides.findFirst(someCriteria);

// rules
if (o.isNull) {
  o := createOverrideSomehowThatMachesAboveCriteria()
  nlist<Overrides> tmp := new arraylist<node<Override>>(copy: currentOverrides);
  tmp.add(a);
  this.overrides := tmp;
}
````

I created the copy because this way the only actual model change is the last assignment.

I agree we would also need to remove an `Override` eventually.

**Comment by marcham** [comment]
small typo: should be `tmp.add(o)` I guess?

**Comment by WimBast** [comment]
nlist<Override> normalOverrides := .....;

this.overrrides := this.overrides.where(...is fake...).concat(normalOverrides);

Should be sufficient.

**Comment by enikao** [comment]
Thanks @marcham, I fixed my example above.

**Comment by WimBast** [comment]
````
// attributes

// rules

{ 
  nlist<Override> currentOverrides = this.overrides; 
  node<Override> o = currentOverrides.findFirst({~it => ...; }); 
  if (o.isNull) { 
    o = ...; 
    this.overrides := currentOverrides.concat(new singleton<node<Override>>(o)); 
  } 
}

````

**Comment by WimBast** [comment]
I your example #5, there is another rule (in the 'working' branch) that defines the value for 'overrides'. That is not a problem as long as both rules that equalize 'overrides' can hold at the same time.

**Comment by enikao** [comment]
I started to write down some of the things we can do in Dclare at https://github.com/enikao/DclareForMPS/wiki/Hints-on-using-DclareForMPS.
