### ISSUE TITLE
primitive types (e.g. boolean) are implemented by boxed types (Boolean) but NPE's can cause unexpected results

### ISSUE THREAD

**Issue by tombrus** [ModelingValueGroup/dclareForMPS#75]
I had the following problem:

Module ruleset:

`attr list<model> sourceModels := this.models.where({~m => m.generationNeeded; });` 

Model ruleset:

`attr boolean generationNeeded := !this.name.endsWith(".service");`

Now when one of the models in `this.models` has a `null` in `generationNeeded`, the whole `where` is skipped and `sourceModels` always stays the empty list forever.

I guess the handling should be more defensive for example `null` values might better be interpreted as `false`. But this is only a wild guess.

**Comment by Gattag** [comment]
#93 might help address this issue
