### ISSUE TITLE
rules in composite attributes are not always activated

### ISSUE THREAD

**Issue by tombrus** [ModelingValueGroup/dclareForMPS#81]
This is a bit vague, but @WimBast and I already looked at this together in an example where I had a statement list inside a quotation that should pick up all statement lists from a list of contained concepts. At random some subconcepts did not get their statements added to the statement list.
@WimBast knows under what conditions this phenomenon surfaces :)

**Comment by WimBast** [comment]
Cannot reproduce anymore. Probably caused by fix in reduce() in MutableTransaction.
